MVCProje/MVCProje/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccesLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProje.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }
        [HttpGet]

        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryvalidator = new CategoryValidator();
            ValidationResult result = categoryvalidator.Validate(p);
            if (result.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryvalue = cm.GetByID(id);
            cm.CategoryDelete(categoryvalue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryvalue = cm.GetByID(id);
            return View(categoryvalue);
        }
        [HttpPost]
        public ActionResult EditCategory(Category p)
        {
            cm.CategoryUpdate(p);
            return RedirectToAction("Index");
           
        }
    }
}

MVCProje/MVCProje/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccesLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProje.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCategoryList()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            //cm.CategoryAddBL(p);
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult resultsonuclar = categoryValidator.Validate(p);
            if(resultsonuclar.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("GetCategoryList");
            }
            else
            {
                foreach (var item in resultsonuclar.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MVCProje/MVCProje/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProje.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCProje/MVCProje/Controllers/IstatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccesLayer.Concrete;

namespace MVCProje.Controllers
{
    public class IstatistikController : Controller
    {
        Context db = new Context();
        
        public ActionResult Index()
        {
            var yazarsayisi = db.Writers.Count().ToString();
            ViewBag.y1 = yazarsayisi;

            var basliksayisi = db.Contents.Count().ToString();
            ViewBag.b1 = basliksayisi;

            var kategorisayisi = db.Categories.Count().ToString();
            ViewBag.k1 = kategorisayisi;

            var kategoribaslikfazla = db.Headings.GroupBy(x => x.Category.CategoryName).OrderByDescending(z => z.Count()).Select(y => y.Key).FirstOrDefault();
            ViewBag.kbf1 = kategoribaslikfazla;

            DateTime bugun = DateTime.Today;
            var bugunbaslik = db.Headings.Count(x => x.HeadingDate == bugun).ToString();
            ViewBag.b1 = bugunbaslik;


            var yazilimveri = db.Headings.Count(x => x.Category.CategoryName == "Yazılım").ToString();
            ViewBag.yaz1 = yazilimveri;

            var egitimveri = db.Headings.Count(x => x.Category.CategoryName == "Eğitim").ToString();
            ViewBag.yaz2 = egitimveri;

            var tiyatroveri = db.Headings.Count(x => x.Category.CategoryName == "Tiyatro").ToString();
            ViewBag.yaz3 = tiyatroveri;

            var kitapveri = db.Headings.Count(x => x.Category.CategoryName == "Kitap").ToString();
            ViewBag.yaz4 = kitapveri;

            var sporveri = db.Headings.Count(x => x.Category.CategoryName == "Spor").ToString();
            ViewBag.yaz5 = sporveri;

            var filmveri = db.Headings.Count(x => x.Category.CategoryName == "Film").ToString();
            ViewBag.yaz6 = filmveri;

            var teknolojiveri = db.Headings.Count(x => x.Category.CategoryName == "Teknoloji").ToString();
            ViewBag.yaz7 = teknolojiveri;

            var encokyorum = db.Contents.GroupBy(x => x.Heading.HeadingName).OrderByDescending(z => z.Count()).Select(y => y.Key).FirstOrDefault();
            ViewBag.yorum1 = encokyorum;

            var aharfi = (from x in db.Writers where x.WriterName.Contains("a") select x).Count().ToString();
            ViewBag.a1 = aharfi;

            var durumtrue = Convert.ToInt32(db.Categories.Count(x => x.CategoryStatus == true));
            var durumfalse = Convert.ToInt32(db.Categories.Count(x => x.CategoryStatus == false));
            int sonuc = durumtrue - durumfalse;
            ViewBag.goster = sonuc;







            return View();
        }
    }
}

MVCProje/MVCProje/Views/AdminCategory/AddCategory.cshtml
@model EntitiyLayer.Concrete.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<h1>YENİ KATEGORİ EKLEME SAYFASI</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı:")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /><br />
        <button class="btn btn-success">KAYDET</button>

    </div>
}

MVCProje/MVCProje/Views/AdminCategory/EditCategory.cshtml
@model EntitiyLayer.Concrete.Category
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>KATEGORİ GÜNCELLEME SAYFASI</h2>

@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
            {
    <div class="form-group">
        @Html.Label("Kategori ID:")
        @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })
     
        <br /><br />
        @Html.Label("Kategori Adı:")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Kategori Açıklama:")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br />
        <button class="btn btn-success">GÜNCELLE</button>

    </div>
            }

MVCProje/MVCProje/Views/AdminCategory/Index.cshtml
@using EntitiyLayer.Concrete
@model List<Category>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />


<h2>MVC KAMP TABLO ÖRNEĞİ-KATEGORİ</h2>
<br />
<table class="table table-bordered table-hover table-striped">
    <tr>
        <th>#</th>
        <th>AD</th>
        <th>AÇIKLAMA</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>BAŞLIKLAR</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryID</th>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDescription</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger" >SİL</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-warning">GÜNCELLE</a></td>
            <td><a href="#" class="btn btn-primary">BAŞLIKLAR</a></td>
        </tr>
    }

</table>

<a href="/AdminCategory/AddCategory" class="btn btn-primary">YENİ KATEGORİ</a>

MVCProje/MVCProje/Views/Category/AddCategory.cshtml
@model EntitiyLayer.Concrete.Category

@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h1>YENİ KATEGORİ EKLEME SAYFASI</h1>
<br />
@using(Html.BeginForm("AddCategory","Category",FormMethod.Post))
 {
    <div class="form-group">
        @Html.Label("Kategori Adı:")
        @Html.TextBoxFor(x=>x.CategoryName)
        @Html.ValidationMessageFor(x=>x.CategoryName)
        <br /><br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextBoxFor(x=>x.CategoryDescription)
        @Html.ValidationMessageFor(x=>x.CategoryDescription)
        <br /><br />
        <button>KAYDET</button>
            
    </div>
            

 }
@*<form class="form-group" method="post">
    <input type="text" placeholder="Kategori Adı" class="form-control" name="CategoryName" />
    <br />
    <input type="text" placeholder="Kategori Adı" class="form-control" name="CategoryDescription" />
    <br />
    <button class="btn btn-primary">EKLE</button>
</form>*@

MVCProje/MVCProje/Views/Category/GetCategoryList.cshtml
@using EntitiyLayer.Concrete
@model List<Category>


@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<h2>MVC KAMP TABLO ÖRNEĞİ-KATEGORİ</h2>
<br />
<table class="table table-bordered table-hover table-striped"  >
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>AÇIKLAMA</th>
        <th>DURUM</th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.CategoryID</td>
                    <td>@item.CategoryName</td>
                    <td>@item.CategoryDescription</td>
                    <td>@item.CategoryStatus</td>
                </tr>
            }

</table>
<br />
<a href="/Category/AddCategory" class="btn btn-primary">YENİ KATEGORİ</a>

MVCProje/MVCProje/Views/Category/Index.cshtml
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h2>MVC KAMP TABLO ÖRNEĞİ-KATEGORİ</h2>
<br />
<table class="table table-bordered table-hover table-striped"  >
    <tr>
        <th>ID</th>
        <th>ADI</th>
        <th>AÇIKLAMA</th>
        <th>DURUM</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Açıklama</td>
        <td>True</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Spor</td>
        <td>Açıklama</td>
        <td>True</td>
    </tr>
</table>

MVCProje/MVCProje/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCProje/MVCProje/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCProje/MVCProje/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCProje/MVCProje/Views/Istatistik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<hr />
<h2 style="text-align:center;">İSTATİSTİKLER</h2>
<hr />
<br />
<br />

<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h3>@ViewBag.k1</h3>

                <p style="font-size:15px;">Kategori Sayısı</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>

    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-black">
            <div class="inner">
                <h3>@ViewBag.b1</h3>

                <p style="font-size:15px;">Başlık Sayısı</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h3>@ViewBag.kbf1</h3>

                <p style="font-size:15px;">En fazla başlığın bulunduğu kategori</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>
    <!-- ./col -->

    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-danger">
            <div class="inner">
                <h3>@ViewBag.y1</h3>

                <p style="font-size:15px;">Yazar Sayısı</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-gradient-teal">
            <div class="inner">
                <h3>@ViewBag.yaz1</h3>

                <p style="font-size:15px;">Yazılım kategorisindeki toplam başlık</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <!--<div class="col-lg-3 col-6">-->
        <!-- small box -->
        <!--<div class="small-box bg-gradient-teal">
            <div class="inner">
                <h3>@ViewBag.yaz2</h3>

                <p style="font-size:15px;">Eğitim kategorisindeki toplam başlık</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>-->
    <!-- ./col -->
    <!-- ./col -->
    <!--<div class="col-lg-3 col-6">-->
        <!-- small box -->
        <!--<div class="small-box bg-gradient-teal">
            <div class="inner">
                <h3>@ViewBag.yaz3</h3>

                <p style="font-size:15px;">Tiyatro kategorisindeki toplam başlık</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>-->
    <!-- ./col -->
    <!-- ./col -->
    <!--<div class="col-lg-3 col-6">-->
        <!-- small box -->
        <!--<div class="small-box bg-gradient-teal">
            <div class="inner">
                <h3>@ViewBag.yaz4</h3>

                <p style="font-size:15px;">Kitap kategorisindeki toplam başlık</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>-->
    <!-- ./col -->
    <!-- ./col -->
    <!--<div class="col-lg-3 col-6">-->
        <!-- small box -->
        <!--<div class="small-box bg-gradient-teal">
            <div class="inner">
                <h3>@ViewBag.yaz5</h3>

                <p style="font-size:15px;">Spor kategorisindeki toplam başlık</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>-->
    <!-- ./col -->
    <!-- ./col -->
    <!--<div class="col-lg-3 col-6">-->
        <!-- small box -->
        <!--<div class="small-box bg-gradient-teal">
            <div class="inner">
                <h3>@ViewBag.yaz6</h3>

                <p style="font-size:15px;">Film kategorisindeki toplam başlık</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>-->
    <!-- ./col -->
    <!-- ./col -->
    <!--<div class="col-lg-3 col-6">-->
        <!-- small box -->
        <!--<div class="small-box bg-gradient-teal">
            <div class="inner">
                <h3>@ViewBag.yaz7</h3>

                <p style="font-size:15px;">Teknoloji kategorisi toplam başlık</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>-->
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-gradient-maroon">
            <div class="inner">
                <h3>@ViewBag.yorum1</h3>

                <p style="font-size:15px;">En çok yorum yapılan başlık</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-gradient-olive">
            <div class="inner">
                <h3>@ViewBag.b1</h3>

                <p style="font-size:15px;">Bugün açılan başlık sayısı</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box badge-secondary">
            <div class="inner">
                <h3>@ViewBag.a1</h3>

                <p style="font-size:15px;">Yazar adında a harfi geçen yazar sayısı</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-navy">
            <div class="inner">
                <h3>@ViewBag.goster</h3>

                <p style="font-size:15px;">Kategori true-false farkı</p>
            </div>

            <a href="#" class="small-box-footer">More info </a>
        </div>
    </div>
    <!-- ./col -->

</div>

MVCProje/MVCProje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>